apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  labels:
    name: metallb-config
spec:
  project: default
  source:
    repoURL: https://github.com/tchristerus/argocd-test-config.git
    targetRevision: HEAD
    path: infra-apps
    directory:
      jsonnet:
        extVars:
          - name: config_file
            value: metallb-ip-config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system # Installeer de configuratie in de metallb-system namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=false