apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-software
  namespace: argocd
  labels:
    name: metallb
spec:
  project: default
  source:
    repoURL: https://github.com/metallb/metallb.git
    targetRevision: v0.14.3
    # Installeert de Pods en Services
    path: config/manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true