# infra-apps/traefik-controller.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress-controller
  namespace: argocd
  labels:
    name: ingress-controller
spec:
  project: default
  loadBalancerIP: 65.108.146.3
  source:
    # Official Traefik Helm chart repository
    repoURL: https://traefik.github.io/charts
    targetRevision: 29.0.0 # Use a stable chart revision
    chart: traefik
  destination:
    server: https://kubernetes.default.svc
    # Deploy Traefik into its own dedicated namespace
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Use the explicit --set options for maximum reliability:
      - --set service.loadBalancerIP=65.108.146.3
      - --set kubernetes.ingress.enableGatewayAPI=false